# Generated by Django 4.2.6 on 2023-10-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='plogin',
            field=models.BooleanField(default=False, null=True, verbose_name='Profile Login'),
        ),
    ]
